/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import estructuras.ArbolAVL;
import estructuras.ArbolB;
import estructuras.ArbolBB;
import estructuras.ListaAdyacencia;
import estructuras.ListaDoble;
import estructuras.ListaSimple;
import estructuras.MatrizDispersa;
import estructuras.TablaHash;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import nodos.NodoAVL;
import objetos.Capa;
import objetos.Imagen;

/**
 *
 * @author hugom
 */
public class InicioUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InicioUsuario
     */
    private ImageIcon imagen;
    private Image img;
    private Icon icono;
    private MetodosUsuario metodos;
    private ArbolBB arbolitoBB;
    private ArbolAVL arbolitoAVL;
    private ListaDoble listaAlbumes;
    private ArbolB arbolitoB;
    private TablaHash tablaMsj;
    private ListaAdyacencia listaAdyacencia;
    private String recorrido = "";
    private String recorridoListaCapas = "";
    private JScrollPane sp;
    private JScrollPane falso;
    JLabel labelTitulo;
    JTable t;
    
    public InicioUsuario(ArbolB arbolitoB, ArbolAVL arbolitoAVL, ArbolBB arbolitoBB, ListaDoble listaAlbumes,
    TablaHash tablaMsj, ListaAdyacencia listaAdyacencia) {
        initComponents();
        // this.jPanel5.add(this.cargarTabla());
        
        // this.jPanel4
        this.pintarImagen(this.lblCargarImg, getClass().getResource("/image/imagen.png"));
        this.pintarImagen(this.lblCargarCapas, getClass().getResource("/image/capa.png"));
        this.pintarImagen(this.lblCargarAlbumes, getClass().getResource("/image/album-de-fotos.png"));
        metodos = new MetodosUsuario();
        this.arbolitoAVL = arbolitoAVL;
        this.arbolitoBB = arbolitoBB;
        this.listaAlbumes = listaAlbumes;
        this.arbolitoB = arbolitoB;
        this.tablaMsj = tablaMsj;
        this.listaAdyacencia = listaAdyacencia;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRecorrido = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCargarImg = new javax.swing.JLabel();
        lblCargarCapas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCargarAlbumes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroCapas = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnRecorridoLimitado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdImg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdCapas = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblRecorrido = new javax.swing.JTextArea();
        btnRecorridoLimitado1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblEstructura = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtIdCapaL = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtIdImagenL = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtIdNuevaImg = new javax.swing.JTextField();
        txtCapasNuevaImg = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtIdImgEliminar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnTop5Capas = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton14 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("Carga Masiva");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel5.setText("Imagenes");

        lblCargarImg.setText(".");
        lblCargarImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCargarImgMouseClicked(evt);
            }
        });

        lblCargarCapas.setText(".");
        lblCargarCapas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCargarCapasMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel6.setText("Capas");

        lblCargarAlbumes.setText(".");
        lblCargarAlbumes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCargarAlbumesMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel7.setText("Álbumes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargarCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(312, 312, 312)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(313, 313, 313)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargarAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(69, 69, 69)
                        .addComponent(lblCargarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(69, 69, 69)
                        .addComponent(lblCargarCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(69, 69, 69)
                        .addComponent(lblCargarAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144))
        );

        jTabbedPane1.addTab("Carga masiva", jPanel1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Por recorrido limitado");

        groupRecorrido.add(jRadioButton1);
        jRadioButton1.setText("PreOrden");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });

        groupRecorrido.add(jRadioButton2);
        jRadioButton2.setText("InOrden");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });

        groupRecorrido.add(jRadioButton3);
        jRadioButton3.setText("PostOrden");
        jRadioButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton3StateChanged(evt);
            }
        });

        btnRecorridoLimitado.setBackground(new java.awt.Color(255, 255, 153));
        btnRecorridoLimitado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecorridoLimitado.setText("Generar Imagen");
        btnRecorridoLimitado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecorridoLimitadoMouseClicked(evt);
            }
        });
        btnRecorridoLimitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridoLimitadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de recorrido");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Numero de capas");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Por árbol de imágenes");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ID de la imagen");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Por capas");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ID´s de las capas separadas por comas");

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Generar Imagen");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Generar Imagen");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblImagen.setText(".");

        lblRecorrido.setEditable(false);
        lblRecorrido.setColumns(20);
        lblRecorrido.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblRecorrido.setRows(5);
        jScrollPane1.setViewportView(lblRecorrido);

        btnRecorridoLimitado1.setBackground(new java.awt.Color(255, 204, 51));
        btnRecorridoLimitado1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecorridoLimitado1.setText("Abrir imagen");
        btnRecorridoLimitado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecorridoLimitado1MouseClicked(evt);
            }
        });
        btnRecorridoLimitado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridoLimitado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtIdImg, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3))
                            .addComponent(btnRecorridoLimitado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(txtNumeroCapas))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(563, 563, 563)
                        .addComponent(btnRecorridoLimitado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(400, 400, 400))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(btnRecorridoLimitado1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(txtNumeroCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecorridoLimitado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdImg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(23, 23, 23)
                .addComponent(txtIdCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Generacion imagenes", jPanel2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Visualizacion de estructuras");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Ver árbol de imagenes (AVL)");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblEstructura.setText(".");

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Ver árbol de capas (ABB)");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Abrir imagen");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Ver listado de albumes");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Ver capa");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("ID de la capa (Capa a nivel logico)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("ID de la imagen (AVL y capas que conforman a esa imagen)");

        jButton8.setBackground(new java.awt.Color(153, 255, 153));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Ver imagen");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(txtIdCapaL))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdImagenL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEstructura, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtIdCapaL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdImagenL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblEstructura, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Visualizacion estructuras", jPanel3);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel15.setText("Eliminar imágen");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel16.setText("Registrar imágen");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("ID de la nueva imagen (debe ser unico)");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Capas separadas por coma (Ej. 1,2,3)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("ID de la imagen");

        jButton9.setBackground(new java.awt.Color(255, 255, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Registrar imagen");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 102));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Eliminar imagen");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIdNuevaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCapasNuevaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIdImgEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(832, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(822, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtIdNuevaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txtCapasNuevaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(txtIdImgEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel16)
                    .addContainerGap(572, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Gestion imagenes", jPanel4);

        btnTop5Capas.setBackground(new java.awt.Color(204, 255, 102));
        btnTop5Capas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTop5Capas.setText("Top 5 de imagenes con mas capas");
        btnTop5Capas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTop5CapasMouseClicked(evt);
            }
        });
        btnTop5Capas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTop5CapasActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(204, 255, 102));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("Capas que son hojas");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 255, 102));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("Profundidad del arbol de capas");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Tipo de recorrido");

        groupRecorrido.add(jRadioButton4);
        jRadioButton4.setText("PreOrden");
        jRadioButton4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton4StateChanged(evt);
            }
        });

        groupRecorrido.add(jRadioButton5);
        jRadioButton5.setText("InOrden");
        jRadioButton5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton5StateChanged(evt);
            }
        });

        groupRecorrido.add(jRadioButton6);
        jRadioButton6.setText("PostOrden");
        jRadioButton6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton6StateChanged(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(204, 255, 102));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("Listar capas");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setText("Listar capas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTop5Capas, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton6))
                    .addComponent(jLabel20)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(1120, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnTop5Capas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel21)
                .addGap(30, 30, 30)
                .addComponent(jLabel20)
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel5);

        jButton11.setBackground(new java.awt.Color(255, 204, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("Cerrar Sesion");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(624, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sesion", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCargarCapasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCargarCapasMouseClicked
        // TODO add your handling code here:

        try {
            this.metodos.openFile("capas", arbolitoAVL, arbolitoBB, listaAlbumes);
        } catch (Exception e) {
            System.out.println(e);
        }

        /*if (content != null) {
            this.txtEntrada.setText(content);
        }*/
    }//GEN-LAST:event_lblCargarCapasMouseClicked

    private void lblCargarImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCargarImgMouseClicked
        // TODO add your handling code here:
        try {
            this.metodos.openFile("img",arbolitoAVL, arbolitoBB, listaAlbumes);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_lblCargarImgMouseClicked

    private void lblCargarAlbumesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCargarAlbumesMouseClicked
        // TODO add your handling code here:
        try {
            this.metodos.openFile("albumes", arbolitoAVL, arbolitoBB, listaAlbumes);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_lblCargarAlbumesMouseClicked

    private void btnRecorridoLimitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridoLimitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecorridoLimitadoActionPerformed

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        // TODO add your handling code here:
        this.recorrido = "pre";
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        // TODO add your handling code here:
        this.recorrido = "in";
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton3StateChanged
        // TODO add your handling code here:
        this.recorrido = "post";
    }//GEN-LAST:event_jRadioButton3StateChanged

    private void btnRecorridoLimitadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecorridoLimitadoMouseClicked
        // TODO add your handling code here:
        System.out.println("SE ENVIO EL RECORRIDO LIMITADO");
        System.out.println(this.recorrido);
        System.out.println(this.txtNumeroCapas.getText());
        String recorridoStr = "";
        try {
            int numeroCapas = Integer.parseInt(this.txtNumeroCapas.getText());
            if(null != this.recorrido) switch (this.recorrido) {
                case "in":
                    recorridoStr = this.arbolitoBB.inOrden(numeroCapas);
                    this.lblRecorrido.setText("Recorrido InOrden: " + recorridoStr);
                    break;
                case "pre":
                    recorridoStr = this.arbolitoBB.preOrden(numeroCapas);
                    this.lblRecorrido.setText("Recorrido PreOrden: " + recorridoStr);
                    break;
                case "post":
                    recorridoStr = this.arbolitoBB.postOrden(numeroCapas);
                    this.lblRecorrido.setText("Recorrido PostOrden: " + recorridoStr);
                    break;
                default:
                    break;
            }
            this.pintarImagen(this.lblImagen, "prueba.png");
        } catch(Exception e) {
            
        }
    }//GEN-LAST:event_btnRecorridoLimitadoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            this.lblRecorrido.setText("Recorrido: " + this.txtIdCapas.getText());
            String[] idCapas = this.txtIdCapas.getText().split(",");
            MatrizDispersa matriz = new MatrizDispersa();
            for(String idCapa: idCapas) {
                int id = Integer.parseInt(idCapa.trim());
                Capa capaEncontrada = arbolitoBB.buscar(id);
                capaEncontrada.getPixeles().recorrerMatriz(matriz);
            }
            matriz.generarTabla();
            this.pintarImagen(this.lblImagen, "prueba.png");
        } catch(Exception e) {
            
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            int idImg = Integer.parseInt(txtIdImg.getText());
            NodoAVL imgEncontrada = this.arbolitoAVL.buscar(idImg);
            if(imgEncontrada != null) {
                String recorridoStr = imgEncontrada.getImg().getCapas().amplitud();
                this.lblRecorrido.setText("Recorrido en amplitud: " + recorridoStr);
                ImageIcon icon = new ImageIcon("prueba.png");                
                this.pintarImagen(this.lblImagen, "prueba.png");
            }
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.arbolitoAVL.generarAVL();
        this.pintarImagen(this.lblEstructura, "reporte.png");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        this.arbolitoBB.generarABB(true, null);
        this.pintarImagen(this.lblEstructura, "reporte.png");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {

            File objetofile = new File ("reporte.png");
            Desktop.getDesktop().open(objetofile);

        }catch (IOException ex) {
            System.out.println(ex);

        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        this.listaAlbumes.codigoGraphviz();
        this.pintarImagen(this.lblEstructura, "reporte.png");
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        try {
            String idCapa = this.txtIdCapaL.getText();
            Capa capaEncontrada = arbolitoBB.buscar(Integer.parseInt(idCapa.trim()));
            // capaEncontrada.getPixeles().imprimir();
            capaEncontrada.getPixeles().generarGraphvizLogico();
            this.pintarImagen(this.lblEstructura, "reporte.png");
        } catch(Exception e) {
            
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        this.txtIdImagenL.getText();
        try {
            this.arbolitoAVL.generarAVLCapa(Integer.parseInt(this.txtIdImagenL.getText().trim()));
            this.pintarImagen(this.lblEstructura, "reporte.png");
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        try {
            
            NodoAVL img = this.arbolitoAVL.buscar(Integer.parseInt(this.txtIdNuevaImg.getText().trim()));
            if (img == null) {
                String[] idCapas = this.txtCapasNuevaImg.getText().split(",");
                ArbolBB arbolCapas = new ArbolBB();
                for(String idCapa: idCapas) {                
                    Capa capaEncontrada = arbolitoBB.buscar(Integer.parseInt(idCapa.trim()));
                    arbolCapas.insertar(capaEncontrada);     
                }
                Imagen imgNueva = new Imagen(Integer.parseInt(this.txtIdNuevaImg.getText().trim()), arbolCapas);
                this.arbolitoAVL.insertar(imgNueva);
                JOptionPane.showMessageDialog(null, "Imagen creada con exito");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Imagen no encontada verifique el que el ID exista");
        }
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        try {
            this.listaAlbumes.eliminarImagen(Integer.parseInt(this.txtIdImgEliminar.getText().trim()));
            this.arbolitoAVL.eliminar(Integer.parseInt(this.txtIdImgEliminar.getText().trim()));
            JOptionPane.showMessageDialog(null, "Imagen eliminada con exito");
            // this.pintarImagen(this.lblEstructura, "reporte.png");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Imagen no encontada verifique el que el ID exista");
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void btnTop5CapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTop5CapasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTop5CapasActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jRadioButton4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton4StateChanged
        // TODO add your handling code here:
        this.recorridoListaCapas = "pre";
    }//GEN-LAST:event_jRadioButton4StateChanged

    private void jRadioButton5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton5StateChanged
        // TODO add your handling code here:
        this.recorridoListaCapas = "in";
    }//GEN-LAST:event_jRadioButton5StateChanged

    private void jRadioButton6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton6StateChanged
        // TODO add your handling code here:
        this.recorridoListaCapas = "post";
    }//GEN-LAST:event_jRadioButton6StateChanged

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnTop5CapasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTop5CapasMouseClicked
        // TODO add your handling code here:
        try {
            if(this.sp != null)
                this.jPanel5.remove(this.sp);
            if(this.labelTitulo != null)
                this.jPanel5.remove(this.labelTitulo);
            this.jPanel5.updateUI();
            ListaSimple top5 = this.arbolitoAVL.top5MasCapas();
            this.jPanel5.add(this.cargarTabla(top5));
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnTop5CapasMouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        try {
            if(this.sp != null)
                this.jPanel5.remove(this.sp);
            if(this.labelTitulo != null)
                this.jPanel5.remove(this.labelTitulo);
            this.jPanel5.updateUI();
            this.jPanel5.add(this.cargarTablaHojas(this.arbolitoBB));
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        try {
            if(this.sp != null)
                this.jPanel5.remove(this.sp);
            if(this.labelTitulo != null)
                this.jPanel5.remove(this.labelTitulo);
            this.jPanel5.updateUI();
            this.jPanel5.add(this.cargarTablaCapas(this.arbolitoBB));
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        try {
            if(this.sp != null)
                this.jPanel5.remove(this.sp);    
            if(this.labelTitulo != null)
                this.jPanel5.remove(this.labelTitulo);
            this.jPanel5.updateUI();
            this.jPanel5.add(this.cargarTablaProfundidad(this.arbolitoBB));
        } catch(Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login(this.arbolitoB, this.tablaMsj, this.listaAdyacencia);
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnRecorridoLimitado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecorridoLimitado1MouseClicked
        // TODO add your handling code here:
        try {

            File objetofile = new File ("prueba.png");
            Desktop.getDesktop().open(objetofile);

        }catch (IOException ex) {
            System.out.println(ex);

        }
    }//GEN-LAST:event_btnRecorridoLimitado1MouseClicked

    private void btnRecorridoLimitado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridoLimitado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecorridoLimitado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public JScrollPane cargarTabla(ListaSimple top5) {
        DefaultTableModel modelo = new DefaultTableModel();
        Object[][] datos
                = {
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},};

        this.falso = new JScrollPane(this.t);

        if (datos != null) {
            String[] columnas = {"TOP", "ID imagen", "Cantidad de capas"};
            this.t = new JTable();
            modelo.setColumnIdentifiers(columnas);
            t.setModel(modelo);
            top5.agregarDatos(modelo);
            // this.agregarDatos(modelo);
            
            // this.t = new JTable(datos, columnas);

            sp = new JScrollPane(this.t);
            sp.setBounds(this.btnTop5Capas.getX() + this.btnTop5Capas.getWidth() + 300, this.btnTop5Capas.getY() + 60, 400, 450);
            sp.setVisible(true);
            // Por ultimo agregamos el ScrollPane que tiene dentro la tabla.
            /*DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            this.t.getColumnModel().getColumn(0).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(1).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(2).setCellRenderer(tcr);

//        t.setEnabled(false);
            this.t.getColumnModel().getColumn(0).setPreferredWidth(100);
            this.t.getColumnModel().getColumn(1).setPreferredWidth(115);
            this.t.getColumnModel().getColumn(2).setPreferredWidth(50);
            // setEventoMouseClicked(this.tblUsuarios);

//        t.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JTableHeader jtableHeader = this.t.getTableHeader();
            jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
            this.t.setTableHeader(jtableHeader);
//        panelProfesores.updateUI();*/
            return sp;
        }

        return falso;

    }
    
    public JScrollPane cargarTablaHojas(ArbolBB hojas) {
        DefaultTableModel modelo = new DefaultTableModel();
        Object[][] datos
                = {
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},};

        this.falso = new JScrollPane(this.t);

        if (datos != null) {
            String[] columnas = {"Numero", "ID de la capa", "Tipo de nodo"};
            this.t = new JTable();
            modelo.setColumnIdentifiers(columnas);
            t.setModel(modelo);
            hojas.capasHojas(modelo);
            // this.agregarDatos(modelo);
            
            // this.t = new JTable(datos, columnas);

            sp = new JScrollPane(this.t);
            sp.setBounds(this.btnTop5Capas.getX() + this.btnTop5Capas.getWidth() + 300, this.btnTop5Capas.getY() + 60, 400, 450);
            sp.setVisible(true);
            // Por ultimo agregamos el ScrollPane que tiene dentro la tabla.
            /*DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            this.t.getColumnModel().getColumn(0).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(1).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(2).setCellRenderer(tcr);

//        t.setEnabled(false);
            this.t.getColumnModel().getColumn(0).setPreferredWidth(100);
            this.t.getColumnModel().getColumn(1).setPreferredWidth(115);
            this.t.getColumnModel().getColumn(2).setPreferredWidth(50);
            // setEventoMouseClicked(this.tblUsuarios);

//        t.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JTableHeader jtableHeader = this.t.getTableHeader();
            jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
            this.t.setTableHeader(jtableHeader);
//        panelProfesores.updateUI();*/
            return sp;
        }

        return falso;

    }
    
    public JScrollPane cargarTablaCapas(ArbolBB hojas) {
        DefaultTableModel modelo = new DefaultTableModel();
        Object[][] datos
                = {
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},};

        this.falso = new JScrollPane(this.t);

        if (datos != null) {
            String[] columnas = {"Numero", "ID de la capa"};
            this.t = new JTable();
            modelo.setColumnIdentifiers(columnas);
            t.setModel(modelo);
            if(this.recorridoListaCapas.equals("pre"))
                hojas.listarCapasPre(modelo);
            else if(this.recorridoListaCapas.equals("in"))
                hojas.listarCapasIn(modelo);
            else if(this.recorridoListaCapas.equals("post"))
                hojas.listarCapasPost(modelo);
            // this.agregarDatos(modelo);
            
            // this.t = new JTable(datos, columnas);

            sp = new JScrollPane(this.t);
            sp.setBounds(this.btnTop5Capas.getX() + this.btnTop5Capas.getWidth() + 300, this.btnTop5Capas.getY() + 60, 400, 450);
            sp.setVisible(true);
            // Por ultimo agregamos el ScrollPane que tiene dentro la tabla.
            /*DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            this.t.getColumnModel().getColumn(0).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(1).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(2).setCellRenderer(tcr);

//        t.setEnabled(false);
            this.t.getColumnModel().getColumn(0).setPreferredWidth(100);
            this.t.getColumnModel().getColumn(1).setPreferredWidth(115);
            this.t.getColumnModel().getColumn(2).setPreferredWidth(50);
            // setEventoMouseClicked(this.tblUsuarios);

//        t.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JTableHeader jtableHeader = this.t.getTableHeader();
            jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
            this.t.setTableHeader(jtableHeader);
//        panelProfesores.updateUI();*/
            return sp;
        }

        return falso;

    }

    public JScrollPane cargarTablaProfundidad(ArbolBB hojas) {
        DefaultTableModel modelo = new DefaultTableModel();
        Object[][] datos
                = {
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},
                    {"2999062130101", "Nombre1", "Apellido1"},};

        this.falso = new JScrollPane(this.t);

        if (datos != null) {
            String[] columnas = {"Nivel", "ID de la capa"};
            this.t = new JTable();
            modelo.setColumnIdentifiers(columnas);
            t.setModel(modelo);   
            this.labelTitulo = new JLabel();
            this.jPanel5.add(labelTitulo);
            hojas.listarCapasAmpli(modelo, this.labelTitulo);;
            // labelTitulo.setBounds(600, 350, 180, 23);
            labelTitulo.setBounds(this.btnTop5Capas.getX() + this.btnTop5Capas.getWidth() + 300, this.btnTop5Capas.getY(), 300, 23);
            
            // this.agregarDatos(modelo);
            
            // this.t = new JTable(datos, columnas);

            sp = new JScrollPane(this.t);
            sp.setBounds(this.btnTop5Capas.getX() + this.btnTop5Capas.getWidth() + 300, this.btnTop5Capas.getY() + 60, 400, 450);
            sp.setVisible(true);
            // labelTitulo.setBounds(20, 5, 180, 23);
            // Por ultimo agregamos el ScrollPane que tiene dentro la tabla.
            /*DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            this.t.getColumnModel().getColumn(0).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(1).setCellRenderer(tcr);
            this.t.getColumnModel().getColumn(2).setCellRenderer(tcr);

//        t.setEnabled(false);
            this.t.getColumnModel().getColumn(0).setPreferredWidth(100);
            this.t.getColumnModel().getColumn(1).setPreferredWidth(115);
            this.t.getColumnModel().getColumn(2).setPreferredWidth(50);
            // setEventoMouseClicked(this.tblUsuarios);

//        t.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JTableHeader jtableHeader = this.t.getTableHeader();
            jtableHeader.setDefaultRenderer(new GestionEncabezadoTabla());
            this.t.setTableHeader(jtableHeader);
//        panelProfesores.updateUI();*/
            return sp;
        }

        return falso;

    }

    public void escalarLabel(JLabel label, String rutaImagen) {
        // label
        this.imagen = new ImageIcon(rutaImagen);
        int altIcon = this.imagen.getIconHeight();
        int anchIcon = this.imagen.getIconWidth();
        int nuevaAlt = 0;
        int nuevaAnc = 0;
        if(altIcon > label.getHeight() && anchIcon < label.getWidth()) {
            int resta = altIcon - label.getHeight();
            nuevaAlt = altIcon - resta;
            nuevaAnc = anchIcon - resta;
        } else if(altIcon < label.getHeight() && anchIcon > label.getWidth()) {
            int resta = anchIcon - label.getWidth();
            nuevaAlt = altIcon - resta;
            nuevaAnc = anchIcon - resta;
        } else if(altIcon > label.getHeight() && anchIcon > label.getWidth()) {
            if(altIcon > anchIcon) {
                int resta = altIcon - label.getHeight();
                nuevaAlt = altIcon - resta;
                nuevaAnc = anchIcon - resta;
            } else {
                int resta = anchIcon - label.getWidth();
                nuevaAlt = altIcon - resta;
                nuevaAnc = anchIcon - resta;
            }            
        } else {
            nuevaAlt = altIcon;
            nuevaAnc = anchIcon;
        }
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        nuevaAnc, 
                        nuevaAlt, 
                        Image.SCALE_DEFAULT
                )
        );
        label.setSize(this.icono.getIconHeight(), this.icono.getIconWidth());
        label.setIcon(this.icono);
        this.repaint();
    }
    
    private void pintarImagen(JLabel lbl, URL ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
        
    }
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecorridoLimitado;
    private javax.swing.JButton btnRecorridoLimitado1;
    private javax.swing.JButton btnTop5Capas;
    private javax.swing.ButtonGroup groupRecorrido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCargarAlbumes;
    private javax.swing.JLabel lblCargarCapas;
    private javax.swing.JLabel lblCargarImg;
    private javax.swing.JLabel lblEstructura;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextArea lblRecorrido;
    private javax.swing.JTextField txtCapasNuevaImg;
    private javax.swing.JTextField txtIdCapaL;
    private javax.swing.JTextField txtIdCapas;
    private javax.swing.JTextField txtIdImagenL;
    private javax.swing.JTextField txtIdImg;
    private javax.swing.JTextField txtIdImgEliminar;
    private javax.swing.JTextField txtIdNuevaImg;
    private javax.swing.JTextField txtNumeroCapas;
    // End of variables declaration//GEN-END:variables


}
